#!/usr/bin/python2
#
# Copyright (C) 2010 Nick Blundell.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
# 
# The GNU GPL is contained in /usr/doc/copyright/GPL on a Debian
# system and in the file COPYING in the Linux kernel source.
# 
# Description:
#
# Author       : Nick Blundell
# Organisation : www.nickblundell.org.uk
#


#
# Main
#

def main():
  # XXX: ???
  try:
    import locale
    locale.setlocale(locale.LC_ALL, '')
  except:
    pass

  from docutils.core import publish_cmdline, default_description, publish_string
  import optparse
  import codecs
  import rst_tex

  # Setup command line options.
  argParser = optparse.OptionParser()
  argParser.add_option("--input", action="store", dest="input")
  argParser.add_option("--output", action="store", dest="output")
  argParser.add_option("--template", action="store", dest="template")
  argParser.add_option("--extension", action="store", dest="extension_module")
  options, args = argParser.parse_args()

  assert options.template, "You must specify a latex template file."
  assert options.input, "You must speciy an input .rst file"
  assert options.output, "You must speciy an output .tex file"
  
  input_string = codecs.open(options.input, "r", "utf-8").read()
  
  # Its useful if we can ignore the lower part of text when reformatting.
  input_string = input_string.split("END_OF_TEXT")[0]

  settings_overrides={
    'input_encoding': 'unicode',
    'output_encoding': 'latin-1', # Latin-1 used in docutils core - latex handles this.
  }
  
  writer = rst_tex.Writer(template=options.template, extension_module=options.extension_module, source_filename=options.input)

  output = publish_string(input_string, writer=writer, settings_overrides=settings_overrides)
  codecs.open(options.output, "w", "latin-1").write(output)

if __name__ == "__main__" :
  main()
